export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_FAILURE="ADMIN_PRODUCT_FAILURE";

// Get req for admin
export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS";

// Patch req for admin
export const ADMIN_EDIT_PRODUCT_SUCCESS="ADMIN_EDIT_PRODUCT_SUCCESS";