export const ADMIN_PRODUCT_REQUEST="ADMIN_PRODUCT_REQUEST";
export const ADMIN_PRODUCT_FAILURE="ADMIN_PRODUCT_FAILURE";

// Get req for admin
export const ADMIN_PRODUCT_SUCCESS="ADMIN_PRODUCT_SUCCESS";

// Patch req for admin
export const ADMIN_EDIT_PRODUCT_SUCCESS="ADMIN_EDIT_PRODUCT_SUCCESS";

// Post request for admin
export const ADMIN_POST_PRODUCT_SUCCESS="ADMIN_EDIT_PRODUCT_SUCCESS";
// Delete req
export const ADMIN_DELETE_PRODUCT_SUCCESS="ADMIN_DELETE_PRODUCT_SUCCESS";
